/**
 * Builds data/words/real.txt and data/words/common.txt from the sources in
 * data/sources/ plus the hand-edited data/allow.txt and data/deny.txt.
 * Run with: npm run build:dictionary
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { DEFAULT_SETTINGS } from "../src/settings.ts";
import { buildWordLists } from "../src/wordlists.ts";

const dataDir = fileURLToPath(new URL("../data/", import.meta.url));
const lines = (path: string) => readFileSync(dataDir + path, "utf8").split("\n");

// The offensive list includes multi-word phrases; only single words matter here.
const offensive = lines("sources/ldnoobw-en.txt").filter((l) => /^[a-z]+$/i.test(l.trim()));

const result = buildWordLists({
  realWords: lines("sources/enable1.txt"),
  frequencyRanked: lines("sources/frequency-3to7.txt")
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => {
      const [word = "", count = "0"] = l.split(" ");
      return [word, Number(count)] as const;
    }),
  allow: lines("allow.txt"),
  deny: lines("deny.txt"),
  offensive,
  commonCutoff: DEFAULT_SETTINGS.dictionary.commonCutoff,
  inflectionMinCount: DEFAULT_SETTINGS.dictionary.inflectionMinCount,
  minLength: DEFAULT_SETTINGS.minWordLength,
  maxLength: DEFAULT_SETTINGS.rackSize,
});

const header = (what: string) =>
  `# Word Trap ${what} word list. Generated by scripts/build-dictionary.ts; do not edit.\n` +
  `# Edit data/allow.txt or data/deny.txt and rebuild instead. Sources and licences: data/SOURCES.md\n`;

writeFileSync(dataDir + "words/real.txt", header("real") + result.real.join("\n") + "\n");
writeFileSync(dataDir + "words/common.txt", header("common") + result.common.join("\n") + "\n");

const s = result.stats;
console.log(
  `real: ${s.real}\ncommon: ${s.common} (${s.fromFrequency} by frequency, ` +
    `${s.fromInflection} inflections, ${s.fromAllow} from allow.txt; ${s.denied} entries in deny.txt)`,
);
